/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.view.usuarios;


import cadastrodeproduto.dao.CadastrarClientes;
import telas.view.produto.*;
import cadastrodeproduto.dao.Cadastrar_produto;
import cadastrodeproduto.pojo.CadProdPOJO;
import cadastrodeproduto.model.CadProdMODEL;
import javax.swing.JOptionPane;
import cadastrodeproduto.dao.Cadastrar_produto;
import cadastrodeproduto.model.CadCliMODEL;
import cadastrodeproduto.pojo.CadCliPOJO;
import com.sun.xml.internal.fastinfoset.EncodingConstants;
/**
 *
 * @author cedup
 */
public class alterarcliente extends javax.swing.JFrame {

    /**
     * Creates new form CafastroProduto
     */
    public alterarcliente(int codigo) {
        initComponents();
        carregardados(codigo);
    }

    
    public void carregardados(int codigo){
    
    if (codigo != 0)
        {
        
            CadastrarClientes pc = new CadastrarClientes();
            CadCliPOJO cpojo = new CadCliPOJO();
            
            cpojo = pc.verificar_login_usuario_unico(codigo);
            TCodAlterarUsuario.setText(""+cpojo.getCodigo());
            TNomeAlterarUsuario.setText(cpojo.getNome());
            TTelefoneAlterarUsuario.setText(""+cpojo.getTelefone());
            TCpfAlterarUsuario.setText(cpojo.getCpf());
            TRgAlterarUsuario.setText(""+cpojo.getRg());
            TEmailAlterarUsuario.setText(cpojo.getEmail());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        TCodAlterarUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        TNomeAlterarUsuario = new javax.swing.JTextField();
        TTelefoneAlterarUsuario = new javax.swing.JTextField();
        LTelefone = new javax.swing.JLabel();
        BAlterarCli = new javax.swing.JButton();
        TCpfAlterarUsuario = new javax.swing.JTextField();
        LCpf = new javax.swing.JLabel();
        TRgAlterarUsuario = new javax.swing.JTextField();
        TEmailAlterarUsuario = new javax.swing.JTextField();
        LRg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TCodAlterarUsuario.setEditable(false);
        TCodAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCodAlterarUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Código do Produto");

        LNome.setText("Nome");

        TNomeAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNomeAlterarUsuarioActionPerformed(evt);
            }
        });

        LTelefone.setText("Telefone");

        BAlterarCli.setText("Alterar");
        BAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlterarCliActionPerformed(evt);
            }
        });

        TCpfAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCpfAlterarUsuarioActionPerformed(evt);
            }
        });

        LCpf.setText("CPF");

        TRgAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRgAlterarUsuarioActionPerformed(evt);
            }
        });

        TEmailAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEmailAlterarUsuarioActionPerformed(evt);
            }
        });

        LRg.setText("RG");

        jLabel4.setText("E-mail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(LRg)
                    .addComponent(LCpf)
                    .addComponent(LTelefone)
                    .addComponent(jLabel2)
                    .addComponent(TCodAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNome)
                    .addComponent(TTelefoneAlterarUsuario)
                    .addComponent(TNomeAlterarUsuario)
                    .addComponent(TCpfAlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(TRgAlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(TEmailAlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(BAlterarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCodAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNomeAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TTelefoneAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCpfAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LRg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TRgAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEmailAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(BAlterarCli)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCodAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCodAlterarUsuarioActionPerformed
 
        
        
 
        
       
    }//GEN-LAST:event_TCodAlterarUsuarioActionPerformed

    private void TNomeAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNomeAlterarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNomeAlterarUsuarioActionPerformed

    private void BAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlterarCliActionPerformed
        
        CadCliPOJO ccp = new CadCliPOJO();
        CadCliMODEL ccm = new CadCliMODEL();
        CadastrarClientes cc = new CadastrarClientes();
        
        ccp.setCodigo(Integer.parseInt(TCodAlterarUsuario.getText()));
        ccp.setNome(TNomeAlterarUsuario.getText());
        ccp.setTelefone(Integer.parseInt(TTelefoneAlterarUsuario.getText()));
        ccp.setCpf(TCodAlterarUsuario.getText());
        ccp.setRg(Integer.parseInt(TRgAlterarUsuario.getText()));
        ccp.setEmail(TEmailAlterarUsuario.getText());
        
        
        try {
            ccm.verificar_campos_cli(ccp);
           int n = cc.alterar_cliente(ccp);
            System.out.println("---");
        
            }catch 
            (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(null, ccp.getErro()+ "Verifique Novamente !","Erro",2);
        }
            
       
        
        
        
        
    }//GEN-LAST:event_BAlterarCliActionPerformed

    private void TCpfAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCpfAlterarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCpfAlterarUsuarioActionPerformed

    private void TRgAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRgAlterarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRgAlterarUsuarioActionPerformed

    private void TEmailAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEmailAlterarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEmailAlterarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterarcliente(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterarCli;
    private javax.swing.JLabel LCpf;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LRg;
    private javax.swing.JLabel LTelefone;
    private javax.swing.JTextField TCodAlterarUsuario;
    private javax.swing.JTextField TCpfAlterarUsuario;
    private javax.swing.JTextField TEmailAlterarUsuario;
    private javax.swing.JTextField TNomeAlterarUsuario;
    private javax.swing.JTextField TRgAlterarUsuario;
    private javax.swing.JTextField TTelefoneAlterarUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
