/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.view.usuarios;


import cadastrodeproduto.dao.CadastrarClientes;
import telas.view.produto.*;
import java.util.List;
import cadastrodeproduto.dao.Cadastrar_produto;
import cadastrodeproduto.pojo.CadCliPOJO;
import cadastrodeproduto.pojo.CadProdPOJO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cedup
 */
public class BuscarCliente extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProduto
     */
    public BuscarCliente() {
        initComponents();
        buscarclientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TTabelaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TPesquisa = new javax.swing.JTextField();
        BExcluir = new javax.swing.JButton();
        BAlterarCli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BPesquisar.setText("Pesquisar");
        BPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPesquisarActionPerformed(evt);
            }
        });

        TTabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "codigo", "nome", "rg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TTabelaClientes);

        jLabel1.setText("Pesquisar Produto");

        TPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TPesquisaKeyReleased(evt);
            }
        });

        BExcluir.setText("Excluir");
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        BAlterarCli.setText("Alterar");
        BAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlterarCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TPesquisa)
                            .addComponent(jLabel1))
                        .addGap(2, 2, 2)
                        .addComponent(BPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BAlterarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPesquisar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(BAlterarCli)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limparTabela()
    {
        if(TTabelaClientes.getRowCount()>0)
        {
            for(int i=TTabelaClientes.getRowCount()-1; i>=0;i--)
            {
                ((DefaultTableModel) TTabelaClientes.getModel()).removeRow(0);
            }
        }
    }
    public void buscarclientes()
    {
        
        CadastrarClientes cc = new CadastrarClientes();
        List list = cc.read(TPesquisa.getText());
        
        
        int num=TTabelaClientes.getSelectedRowCount();
        DefaultTableModel dtm = (DefaultTableModel)TTabelaClientes.getModel();
        limparTabela();
        

        for(int i = 0; i<list.size(); i++){
            //String ferramenta="Sim";
            CadCliPOJO ccp = (CadCliPOJO)list.get(i);
            
            
            
            dtm.addRow(new Object[]{ccp.getCodigo(), ccp.getNome(), ccp.getRg()});
        }
    }
    private void BPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPesquisarActionPerformed
       
        
        buscarclientes();
      
        
        
        
        
        /*
        int linha=TTabelaServicos.getSelectedRow();
        Cadastrar_Servico_Banco ba = new Cadastrar_Servico_Banco();
        List lista=ba.read();
        pojo_servico cad = (pojo_servico)lista.get(linha);
        int codigoid=cad.getCodigoid();
        System.out.println(codigoid);
        */
    }//GEN-LAST:event_BPesquisarActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
        if(TTabelaClientes.getSelectedRow()>=0){
            if(JOptionPane.showConfirmDialog(this, "Deseja realmente Excluir ?")==0){
                CadastrarClientes cc = new CadastrarClientes();
                cc.excluirproduto(Integer.parseInt(""+TTabelaClientes.getValueAt(TTabelaClientes.getSelectedRow(), 0 )));
                limparTabela();
                buscarclientes();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Produto");
        }
            
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlterarCliActionPerformed
       int codigo = Integer.parseInt(""+TTabelaClientes.getValueAt(TTabelaClientes.getSelectedRow(), 0));
       alterarcliente ac = new alterarcliente(codigo);
       ac.setVisible(true);
       buscarclientes();
    }//GEN-LAST:event_BAlterarCliActionPerformed

    private void TPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPesquisaKeyReleased
        buscarclientes();
    }//GEN-LAST:event_TPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterarCli;
    private javax.swing.JButton BExcluir;
    private javax.swing.JButton BPesquisar;
    private javax.swing.JTextField TPesquisa;
    private javax.swing.JTable TTabelaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
