/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.view.usuarios;

import telas.view.produto.CadastroProduto;
import telas.view.produto.BuscarProduto;
import telas.view.produto.alterarproduto;

/**
 *
 * @author LabNTE 9
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BBuscarProdPrincipal = new javax.swing.JButton();
        BCadastrarProdPrincipal = new javax.swing.JButton();
        BBuscarCliPrincipal = new javax.swing.JButton();
        BCadastrarCliPrincipal = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BBuscarProdPrincipal.setText("Buscar Produto");
        BBuscarProdPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarProdPrincipalActionPerformed(evt);
            }
        });

        BCadastrarProdPrincipal.setText("Cadastrar Produto");
        BCadastrarProdPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarProdPrincipalActionPerformed(evt);
            }
        });

        BBuscarCliPrincipal.setText("Buscar Cliente");
        BBuscarCliPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarCliPrincipalActionPerformed(evt);
            }
        });

        BCadastrarCliPrincipal.setText("Cadastrar Cliente");
        BCadastrarCliPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarCliPrincipalActionPerformed(evt);
            }
        });

        jButton5.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BBuscarProdPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCadastrarProdPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBuscarCliPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCadastrarCliPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BBuscarProdPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCadastrarProdPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BBuscarCliPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCadastrarCliPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BBuscarProdPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarProdPrincipalActionPerformed
       
        BuscarProduto bp = new BuscarProduto();
        bp.setVisible(true);
    }//GEN-LAST:event_BBuscarProdPrincipalActionPerformed

    private void BCadastrarProdPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarProdPrincipalActionPerformed
            
        CadastroProduto cp = new CadastroProduto();
        cp.setVisible(true);
    }//GEN-LAST:event_BCadastrarProdPrincipalActionPerformed

    private void BBuscarCliPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarCliPrincipalActionPerformed
        
            BuscarCliente bc = new BuscarCliente();
            bc.setVisible(true);
            
    }//GEN-LAST:event_BBuscarCliPrincipalActionPerformed

    private void BCadastrarCliPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarCliPrincipalActionPerformed
            CadastroCliente cc = new CadastroCliente();
            cc.setVisible(true);
    }//GEN-LAST:event_BCadastrarCliPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscarCliPrincipal;
    private javax.swing.JButton BBuscarProdPrincipal;
    private javax.swing.JButton BCadastrarCliPrincipal;
    private javax.swing.JButton BCadastrarProdPrincipal;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
